project_id = "ytiwuzdleyqfzwrwgtbc"

[functions]
  [functions.analyze-clothing]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.moderate-message]
    verify_jwt = false
  [functions.outfit-chat]
    verify_jwt = false
  [functions.klaviyo-subscribe]
    verify_jwt = false
  [functions.validate-username]
    verify_jwt = false
